SPEC = Gem::Specification.new do |spec| 
  spec.name = "bcms_intensedebate"
  spec.rubyforge_project = spec.name
  spec.version = "0.5.0"
  spec.summary = "Integrate IntenseDebate commenting into your BrowserCMS site"
  spec.author = "Dan Collis-Puro" 
  spec.email = "dan@collispuro.com" 
  spec.homepage = "http://www.collispuro.com" 
  spec.files += Dir["app/**/*"]
  spec.files += Dir["db/migrate/*.rb"]
  spec.files -= Dir["db/migrate/*_browsercms_*.rb"]
  spec.files -= Dir["db/migrate/*_load_seed_data.rb"]
  spec.files += Dir["lib/bcms_intensedebate.rb"]
  spec.files += Dir["lib/bcms_intensedebate/*"]
  spec.files += Dir["config/initializers/intense_debate_settings.rb"]
  spec.files += Dir["rails/init.rb"]
  spec.files += Dir["public/bcms/intensedebate/**/*"]
  spec.has_rdoc = true
  spec.extra_rdoc_files = ["README.markdown"]
end
